### ISSUE TITLE
报错: Permission denial

### ISSUE THREAD

**Issue by yy249357** [songhanghang/auto_set_proxy#1]
mac使用USB连接小米手机,
执行easyproxy clean
报错: 清除代理成功
Exception occurred while executing 'put':
java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2105)
	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1291)
	at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1245)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:398)
	at android.content.ContentProvider.call(ContentProvider.java:2486)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:522)
	at com.android.providers.settings.SettingsService$MyShellCommand.putForUser(SettingsService.java:375)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:277)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
	at android.os.Binder.shellCommand(Binder.java:935)
	at android.os.Binder.onTransact(Binder.java:819)
	at android.os.Binder.execTransactInternal(Binder.java:1165)
	at android.os.Binder.execTransact(Binder.java:1129)

**Comment by songhanghang** [comment]
开发者模式，开启USB调试（安全设置）即可
